defaults:
  - /model@feature_extractor: frac_seg

_target_: assembly.models.denoiser.DenoiserDiffusion
feature_extractor_ckpt: null
denoiser:
  _target_: assembly.models.denoiser.DenoiserTransformer
  in_dim: ${getIndex:${..feature_extractor.encoder.dec_channels}, 0}
  out_dim: 7
  embed_dim: 512
  num_layers: 6
  num_heads: 8
  dropout_rate: 0.2
  trans_out_dim: 3
  rot_out_dim: 4
noise_scheduler:
  _target_: assembly.models.denoiser.PiecewiseScheduler
  num_train_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: linear
  clip_sample: False
  prediction_type: epsilon
  timestep_spacing: leading
val_noise_scheduler:
  _target_: assembly.models.denoiser.PiecewiseScheduler
  num_train_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: linear
  clip_sample: False
  prediction_type: epsilon
  timestep_spacing: leading
inference_config:
  num_inference_steps: 20
  anchor_free: False
  max_iters: 1
  one_step_init: False
  write_to_json: True
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 2e-4
  betas: [0.95, 0.999]
  weight_decay: 1e-6
  eps: 1e-8
lr_scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: True
  milestones: [900, 1200]
  gamma: 0.5