defaults:
  - encoder: ptv3

_target_: assembly.models.pretraining.FracSeg
pc_feat_dim: 64
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4
  weight_decay: 1e-5
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: True
  T_0: 100
seg_warmup_epochs: 10
grid_size: 0.02