_target_: assembly.backbones.pointtransformerv3.PointTransformerV3
stride:
  - 2
  - 2
  - 2
  - 2
enc_depths:
  - 2
  - 2
  - 2
  - 6
  - 2
enc_num_head:
  - 2
  - 4
  - 8
  - 16
  - 32
enc_patch_size:
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
enc_channels: 
  - 32
  - 64
  - 128
  - 256
  - 512
dec_depths:
  - 2
  - 2
  - 2
  - 2
dec_num_head:
  - 4
  - 4
  - 8
  - 16
dec_patch_size:
  - 1024
  - 1024
  - 1024
  - 1024
dec_channels:
  - ${...pc_feat_dim}
  - 64
  - 128
  - 256